<a href="https://colab.research.google.com/github/aborundiya/NeuralNetwork/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np 
import matplotlib.pyplot as plt 

#Initialize The Tensors

In [2]:
x = torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.3939, 0.3211],
        [0.4320, 0.0507],
        [0.8034, 0.0672]])


In [3]:
x =torch.empty(3,2)
print(x)
x = torch.zeros_like(x)
print(x)

tensor([[4.7190e-36, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
x = torch.linspace(0,1,steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [5]:
x = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [6]:
print(x.size())
print(x[:,1])
print(x[0,:])

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [7]:
print(x)
y = x.view(-1,6)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])


In [8]:
x = torch.ones(3,2)
y = torch.ones(3,2)
print(x+y)
print(x-y)
print(x*y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [9]:
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [10]:
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [11]:
x = torch.tensor([[1,2],[3,4],[5,6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
print(x[2,1])

tensor(6)


#Numpy and Tensor 

In [0]:
x_np = x.numpy()

In [14]:
print(type(x),type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]


In [15]:
a = np.random.rand(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)

[0.4060757  0.01421881 0.10502138 0.88720973 0.07010737]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([0.4061, 0.0142, 0.1050, 0.8872, 0.0701], dtype=torch.float64)


In [16]:
%%time
for i in range(100):
  a = np.random.randn(100,100)
  b = np.random.randn(100,100)
  c = a + b

CPU times: user 84.2 ms, sys: 1.5 ms, total: 85.7 ms
Wall time: 91.5 ms


In [17]:
%%time 
for i in range(100):
  a = torch.randn([100,100])
  b = torch.randn([100,100])
  c = a + b 

CPU times: user 16.7 ms, sys: 0 ns, total: 16.7 ms
Wall time: 17.8 ms


In [18]:
print(torch.cuda.device_count())

1


In [20]:
print(torch.cuda.device(0))

In [21]:
print(torch.cuda.get_device_name())

Tesla P100-PCIE-16GB


In [0]:
cuda0 = torch.device('cuda:0')

In [0]:
a = torch.ones(3,2, device = cuda0)
b = torch.ones(3,2, device = cuda0)
c = a + b 

In [24]:
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [25]:
%%time 
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  c = a + b 

CPU times: user 1min 21s, sys: 598 ms, total: 1min 21s
Wall time: 1min 21s


In [26]:
%%time 
for i in range(10):
  a = torch.randn([10000,10000])
  b = torch.randn([10000,10000])
  c = a + b 

CPU times: user 13.8 s, sys: 12.6 ms, total: 13.9 s
Wall time: 13.9 s


In [29]:
%%time 
for i in range(10):
  a = torch.randn([10000,10000], device = cuda0)
  b = torch.randn([10000,10000], device = cuda0)

CPU times: user 79 µs, sys: 1.98 ms, total: 2.06 ms
Wall time: 2.52 ms


In [30]:
x = torch.ones(3,2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [31]:
y = x + 5 
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [32]:
z = y*y + 1 
print(z)

tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [34]:
t = torch.sum(z)
print(t)

tensor(222., grad_fn=<SumBackward0>)


In [0]:
t.backward()

In [36]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [38]:
x = torch.ones(3,2,requires_grad=True)
y = x + 5 
r = 1 / (1 + torch.exp(-y))
print(r)
s = torch.sum(r)
s.backward()
print(x.grad)

tensor([[0.9975, 0.9975],
        [0.9975, 0.9975],
        [0.9975, 0.9975]], grad_fn=<MulBackward0>)
tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [39]:
x = torch.ones(3,2,requires_grad=True)
y = x + 5 
r = 1 / (1 + torch.exp(-y))
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


#Autograd examples

In [0]:
x = torch.randn([20,1], requires_grad=True )
y = 3 * x -2 

In [0]:
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.],requires_grad=True)
y_hat = w * x + b 
loss = torch.sum((y_hat - y )**2)


In [42]:
print(loss)

tensor(193.4191, grad_fn=<SumBackward0>)


In [0]:
loss.backward()

In [44]:
print(w.grad, b.grad)

tensor([-40.8023]) tensor([101.7446])


#Autodiff in a loop

In [45]:
learning_rate = 0.01 
w = torch.tensor([1.],requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
print(w.item(), b.item())

for i in range(10):
  x = torch.randn([20,1], requires_grad=True)
  y = 3*x-2
  y_hat = w*x+b
  loss = torch.sum((y_hat - y )**2)
  loss.backward()

  with torch.no_grad():
    w -= learning_rate * w.grad 
    b -= learning_rate * b.grad
  
    w.grad.zero_()
    b.grad.zero_()

  print(w.item(),b.item())



1.0 1.0
1.7669719457626343 -0.2753065824508667
1.954535961151123 -0.8011761903762817
2.496535301208496 -1.3451356887817383
2.65522837638855 -1.5767589807510376
2.6882808208465576 -1.6973870992660522
2.853520154953003 -1.8225734233856201
2.9263105392456055 -1.8763551712036133
2.9875428676605225 -1.938688039779663
2.9939236640930176 -1.9636527299880981
2.989069700241089 -1.9770127534866333
